# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181214_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryaccountdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
