# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181214_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(1, 'credit'), (2, 'debit')], default=1, max_length=50),
        ),
    ]
