# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
    ]
